import sys, os
import pandas as pd
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from core.ask_gpt import ask_gpt
from core.config_utils import load_key
import concurrent.futures

CLEANED_CHUNKS_FILE = "output/log/cleaned_chunks.xlsx"
SENTENCE_TXT_PATH = 'output/log/sentence_splitbymeaning.txt'

def get_semantic_chunk_prompt(words_text, language):
    prompt = f"""
### Role
You are an expert linguist and professional subtitle editor in {language}.

### Task
You will be provided with a raw, continuous stream of words with their index numbers. These words were generated by a speech-to-text model and lack proper punctuation and sentence boundaries.
Your goal is to group these words into grammatically correct, semantically meaningful, and natural sentences.

### Instructions
1. Group the words into complete sentences based on {language} grammar logic.
2. DO NOT change, add, or omit any words from the original text. You MUST use the exact words provided.
3. Keep sentences reasonably short (ideal for subtitles, roughly 5-15 words).
4. For each reconstructed sentence, provide the exact words separated by spaces.
5. Provide your output as a JSON list of strings, where each string is a reconstructed sentence.

### Output Format
```json
{{
    "sentences": [
        "word1 word2 word3",
        "word4 word5 word6 word7"
    ]
}}
```

### Input Words
<words>
{words_text}
</words>

### Answer:
"""
    return prompt.strip()

def chunk_words(words, language):
    words_text = " ".join(words)
    prompt = get_semantic_chunk_prompt(words_text, language)

    def valid_chunk(response_data):
        if 'sentences' not in response_data:
            return {"status": "error", "message": "Missing 'sentences' key."}
        return {"status": "success", "message": "Success"}

    try:
        response = ask_gpt(prompt, response_json=True, log_title='semantic_chunking', valid_def=valid_chunk)
        return response.get('sentences', [words_text])
    except Exception as e:
        print(f"Error during semantic chunking API call: {e}")
        return [words_text]

def split_by_semantic_chunking():
    print("Starting semantic chunking based on word-level tokens...")
    if not os.path.exists(CLEANED_CHUNKS_FILE):
        print(f"Error: {CLEANED_CHUNKS_FILE} not found. Ensure whisperX has run.")
        return

    try:
        df = pd.read_excel(CLEANED_CHUNKS_FILE)
    except Exception:
        df = pd.read_csv(CLEANED_CHUNKS_FILE)

    if 'text' not in df.columns:
        print("Error: 'text' column not found in chunks file.")
        return

    words = df['text'].apply(lambda x: str(x).strip('"')).tolist()
    language = load_key("whisper.detected_language") or "English"

    batch_size = 150
    word_batches = [words[i:i + batch_size] for i in range(0, len(words), batch_size)]

    all_sentences = []

    for idx, batch in enumerate(word_batches):
        print(f"Processing batch {idx+1}/{len(word_batches)}...")
        sentences = chunk_words(batch, language)
        all_sentences.extend(sentences)

    os.makedirs(os.path.dirname(SENTENCE_TXT_PATH), exist_ok=True)
    with open(SENTENCE_TXT_PATH, 'w', encoding='utf-8') as f:
        for sentence in all_sentences:
            f.write(f"{sentence}\n")

    print(f"Semantic chunking completed. Saved to {SENTENCE_TXT_PATH}.")

if __name__ == '__main__':
    split_by_semantic_chunking()
